# VALORES POKEDEX:
pokedex = {
1:{'nome':'Bulbassauro','tipo':'Grama/Veneno',},
2:{'nome':'Ivyssauro','tipo':'Grama/Veneno',},
3:{'nome':'Venussauro','tipo':'Grama/Veneno',},
4:{'nome':'Charizard','tipo':'Fogo',},
5:{'nome':'Charmeleon','tipo':'Fogo',},
6:{'nome':'Charizard','tipo':'Fogo/Voador',},       
7:{'nome':'Squirtle','tipo':'Água',},                           
8:{'nome':'Wartortle','tipo':'Água',},
9:{'nome':'Blastoise','tipo':'Água',},
10:{'nome':'Caterpie','tipo':'Inseto',},            
11:{'nome':'Metapod','tipo':'Inseto',}, 
12:{'nome':'Butterfree','tipo':'Inseto/Voador',},
13:{'nome':'Weedle','tipo':'Inseto/Venenoso',},            
14:{'nome':'Kakuna','tipo':'Inseto/Venenoso',},  
15:{'nome':'Beedrill','tipo':'Inseto/Venenoso',},  
16:{'nome':'Pidgey','tipo':'Normal/Voador',},  
17:{'nome':'Pidgeotto','tipo':'Normal/Voador',},  
18:{'nome':'Pidgeot','tipo':'Normal/Voador',},   
19:{'nome':'Rattata','tipo':'Normal',},    
20:{'nome':'Raticate','tipo':'Normal',},        
21:{'nome':'Spearow','tipo':'Normal/Voador',},
22:{'nome':'Fearow','tipo':'Normal/Voador',},
23:{'nome':'Ekans','tipo':'Venenoso',},  
24:{'nome':'Arbok','tipo':'Venenoso',},  
25:{'nome':'Pikachu','tipo':'Elétrico',},    
    
    }